CREATE TABLE TB_ARTICULOS
            (CODIGO_AR NUMBER(5,0)
            ,DESCRIPCION_AR VARCHAR2(200)
            ,MARCA_AR VARCHAR2(30)
            ,CODIGO_ME NUMBER(3,0)
            ,CODIGO_CA NUMBER(4,0)
            ,FECHA_ING DATE
            ,STOCK_ACTUAL DECIMAL(10,2)
            );  
            
ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_MD NOT NULL)
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL)


ALTER TABLE TB_MEDIDAS MODIFY DESCRIPCION_ME VARCHAR(30)

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_MD NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR2(30);

ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_MD);

CREATE TABLE TB_ARTICULOS
            (CODIGO_AR NUMBER(5,0)
            ,DESCRIPCION_AR VARCHAR2(200)
            ,MARCA_AR VARCHAR2(30)
            ,CODIGO_ME NUMBER(3,0)
            ,CODIGO_CA NUMBER(4,0)
            ,FECHA_ING DATE
            ,STOCK_ACTUAL DECIMAL(10,2)
            );  
            
ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_MD NOT NULL)
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL)


ALTER TABLE TB_MEDIDAS MODIFY DESCRIPCION_ME VARCHAR(30)

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_MD NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR2(30);

ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_MD);



ALTER TABLE TB_ARTICULOS
ADD CONSTRAINT FK_01 
FOREIGN KEY (CODIGO_ME) 
REFERENCES TB_MEDIDAS (CODIGO_MD);

ALTER TABLE TB_ARTICULOS
ADD CONSTRAINT FK_02 
FOREIGN KEY (CODIGO_CA) 
REFERENCES TB_CATEGORIAS (CODIGO_CA);

CREATE TABLE TB_ALMACENES(
    CODIGO_AL NUMBER(2,0) GENERATED ALWAYS AS IDENTITY, 
    DESCRIPTION_AL VARCHAR2(30)
)