CREATE TABLE TB_ARTICULOS
            (CODIGO_AR NUMBER(5,0)
            ,DESCRIPCION_AR VARCHAR2(200)
            ,MARCA_AR VARCHAR2(30)
            ,CODIGO_ME NUMBER(3,0)
            ,CODIGO_CA NUMBER(4,0)
            ,FECHA_ING DATE
            ,STOCK_ACTUAL DECIMAL(10,2)
            );  
            
ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_MD NOT NULL)
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL)


ALTER TABLE TB_MEDIDAS MODIFY DESCRIPCION_ME VARCHAR(30)

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_MD NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR2(30);

ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_MD);

CREATE TABLE TB_ARTICULOS
            (CODIGO_AR NUMBER(5,0)
            ,DESCRIPCION_AR VARCHAR2(200)
            ,MARCA_AR VARCHAR2(30)
            ,CODIGO_ME NUMBER(3,0)
            ,CODIGO_CA NUMBER(4,0)
            ,FECHA_ING DATE
            ,STOCK_ACTUAL DECIMAL(10,2)
            );  
            
ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_MD NOT NULL)
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL)


ALTER TABLE TB_MEDIDAS MODIFY DESCRIPCION_ME VARCHAR(30)

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_MD NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR2(30);

ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_MD);



ALTER TABLE TB_ARTICULOS
ADD CONSTRAINT FK_01 
FOREIGN KEY (CODIGO_ME) 
REFERENCES TB_MEDIDAS (CODIGO_MD);

ALTER TABLE TB_ARTICULOS
ADD CONSTRAINT FK_02 
FOREIGN KEY (CODIGO_CA) 
REFERENCES TB_CATEGORIAS (CODIGO_CA);

CREATE TABLE TB_ALMACENES(
    CODIGO_AL NUMBER(2,0) GENERATED ALWAYS AS IDENTITY, 
    DESCRIPTION_AL VARCHAR2(30)
);


INSERT INTO TB_CATEGORIAS
            (CODIGO_CA
            ,DESCRIPCION) 
      VALUES(3
            ,'EVENTOS'
            );
            
INSERT INTO TB_MEDIDAS
            (CODIGO_MD
            ,ABREBIATURA_ME
            ,DESCRIPCION_ME) 
      VALUES(1
            ,'UND'
            ,'UNIDADES'
            );
            
INSERT INTO TB_MEDIDAS
            (CODIGO_MD
            ,ABREBIATURA_ME
            ,DESCRIPCION_ME) 
      VALUES(4
            ,'LTS'
            ,'LITROS'
            );
            
            
INSERT INTO TB_ARTICULOS
            (CODIGO_AR
            ,DESCRIPCION_AR
            ,MARCA_AR
            ,CODIGO_ME
            ,CODIGO_CA) 
      VALUES(1
            ,'COMPUTADOR'
            ,'ASUS'
            ,1
            ,3
            );
            
BEGIN
    dbms_output.put_line('Hola mundo');
END;

DECLARE

    v_num NUMBER(2) := 10;
    v_cadena VARCHAR(10) := 'Marco';
    v_fecha DATE := SYSDATE;

BEGIN
    dbms_output.put_line('El valor de v_num es ' || v_num);
    dbms_output.put_line('El valor de v_cadena es ' || v_cadena);
    dbms_output.put_line('El valor de v_fecha es ' || v_fecha);

END;

DECLARE

    v_opl NUMBER(2) := &operando1;
    v_op2 NUMBER(2) := &operando2;
    v_sum NUMBER(3);


BEGIN
    v_sum := v_opl + v_op2;
    dbms_output.put_line(v_opl ||' + ' || v_op2 || ' = ' || v_sum);

END;
            
            